### ISSUE TITLE
Feature Request : Randomized Boss location

### ISSUE THREAD

**Issue by Niamek** [slashinfty/sml2randomizer#1]
I think it would be cool to randomize the boss locations.

**Comment by slashinfty** [comment]
Likely requires assembly, which I do not know (yet). Long-term project goal.

**Comment by slashinfty** [comment]
This is a big goal of v2.0, which is under construction. Have a theory, testing soon (tm).

**Comment by slashinfty** [comment]
Implemented in v2.0
